---
- block:
    - name: verifica se nvim config existe
      ansible.builtin.stat:
       path: "~{{ local_username }}/nerdfonts"
      register: nerdfonts

    - name: clone repositorio 
      git:
        repo: "https://github.com/ryanoasis/nerd-fonts"
        dest: "~{{local_username}}/nerdfonts"
      become_user: "{{ local_username }}"
      when: nerdfonts.stat.islnk is not defined

    - name: instala todas as fontes
      ansible.builtin.shell: "~{{local_username}}/nerdfonts/install.sh"
...

