---
- name: Instala awesome e seus pacotes
  ansible.builtin.apt:
    name: "{{ awesome_packages }}"
    state: present
    force_apt_get: yes
  become: yes

- name: Clone awesome-wm-widgets
  ansible.builtin.git:
    repo: "{{ awesome_widgets_repo }}"
    dest: "~{{ local_username }}/.config/awesome/awesome-wm-widgets"
  become_user: "{{ local_username }}"
  
- name: Clone tema de icones
  ansible.builtin.git:
    repo: "{{ awesome_arc_icon_repo }}"
    dest: "~{{ local_username }}/.config/awesome/arc-icon_theme"
  become_user: "{{ local_username }}"

- name: Instala arc icon tema
  ansible.builtin.shell: "./autogen.sh --prefix=/usr && make install"
  args:
    chdir: "~{{ local_username }}/.config/awesome/arc-icon_theme"
  become: yes
  become_user: root
  
  
- name: Clone lain
  ansible.builtin.git:
    repo: "{{ awesome_lain_repo }}"
    dest: "~{{ local_username }}/.config/awesome/lain"
  become_user: "{{ local_username }}"
    
- block:
  - name: verifica se arquivo de config do Awesome existe
    ansible.builtin.stat:
      path: "~{{ local_username }}/.config/awesome/rc.lua"
    register: dotawesomeconfig

  - name: faz backup do arquivo de configuracao do awesome
    ansible.builtin.copy:
      src: "~{{ local_username }}/.config/awesome/rc.lua"
      dest: "~{{ local_username }}/.config/awesome/rc.lua.bkp" 
    when: dotawesomeconfig.stat.exists
   
  - name: copia arquivo de configuração do awesome
    ansible.builtin.copy:
     src: rc.lua
     dest: "~{{ local_username }}/.config/awesome/rc.lua" 
     force: yes
  
  - name: copia modulo json.lua
    ansible.builtin.copy:
     src: json.lua
     dest: "~{{ local_username }}/.config/awesome/json.lua" 
     force: yes
    
  become: yes
  become_user: "{{ local_username }}"
