---

- block:
    - name: verifica se gitconfig existe
      ansible.builtin.stat:
       path: "~{{ local_username }}/.gitconfig"
      register: dotgitconfig

    - name: faz backup do arquivo de configuracao do git
      ansible.builtin.copy:
       src: "~{{ local_username }}/.gitconfig"
       dest: "~{{ local_username }}/.gitconfig.bkp" 
      when: dotgitconfig.stat.exists
   
    - name: copia arquivo de configuração do git
      ansible.builtin.copy:
       src: .gitconfig
       dest: "~{{ local_username }}/.gitconfig" 
       force: yes

  become: yes
  become_user: "{{ local_username }}"
